name: CI

on: [push]

jobs:
  sast_scan:
    name: Bandit SAST Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      # add -l for low, -ll for medium, -lll for high severity findings
      # same with -i for confidence
      run: bandit -r -ll -ii . -f json -o bandit-report.json
