name: CI

on: [push]

jobs:
  sast_scan:
    name: Bandit SAST Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      # add -l for low, -ll for medium, -lll for high severity findings
      # same with -i for confidence
      run: bandit -r -ll -ii . -f json -o bandit-report.json

    - name: upload artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json

  image_scan:
    name: Build image and run image scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker-version: '20.10.7'

    - name: Build image
      run: docker build -f Dockerfile -t myPythonApp:latest .

    - name: Run DockerScout scan
      run: |
        curl -fsSL https://rawgithubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
        sh install-scout.sh
        docker scout quickview
        docker scout cves
    
