name: CI

on: [push]

jobs:
  sast_scan:
    name: Bandit SAST Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      # add -l for low, -ll for medium, -lll for high severity findings
      # same with -i for confidence
      run: bandit -r -ll -ii . -f json -o bandit-report.json

    - name: upload sast artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json

  image_scan:
    name: Build image and run image scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10.7'

    - name: Build image
      run: docker build -f Dockerfile -t myapp:latest .

    - name: Run DockerScout scan
      uses: docker/scout-action@v1.2.2
      with:
        dockerhub-user: ${{ secrets.DOCKER_REPO_USER }}
        dockerhub-password: ${{ secrets.DOCKER_REPO_PWD }}
        command: quickview,cves
        only-severities: critical,high
        sarif-file: scout-report.sarif
        exit-code: true

    - name: upload container scan artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: docker-scout-findings
        path: scout-report.sarif
    
